### ISSUE TITLE
훈련 모델 파라미터

### ISSUE THREAD

**Issue by KangSH9776** [haven-jeon/ko_en_neural_machine_translation#1]
안녕하세요. 훈련 모델 파라미터를 제공 받을 수 있을지 여쭤보고자 질문 남깁니다.

리눅스에서 CUDA OUT OF MEMORY 오류가 나서 훈련을 진행하지 못했습니다.

•models/trained_model.params  모델 파라미터를 어디서 다운로드 할 수 있을까요?

**Comment by haven-jeon** [comment]
CUDA OUT OF MEMORY 라면 배치 사이즈를 줄여서 학습 하시는걸 추천드립니다. 

당시 파라메터가 존재하는지는 찾아봐야 될것 같습니다.

**Comment by KangSH9776** [comment]
'train from null' 을 출력하고 에러가 발생합니다.

range가 맞지 않아 CUDA OUT OF MEMORY를 발생하는 것 같은데 당시 파라메터를 어떻게 생성하나요??

**Comment by haven-jeon** [comment]
혹시 문제가 생기는게 어느 파일의 어느 부분인지 알 수 있을지요?
 
현재 MXNet API 변화가 좀 있어서 고쳐야 될 부분이 있는 걸로 기억합니다. 

참 그리고.. 이왕이면 SOTA로 진행하시는걸 추천드립니다. 

http://gluon-nlp.mxnet.io/examples/machine_translation/transformer.html

**Comment by KangSH9776** [comment]
main 코드에서 MXNet 함수가 gpu를 불러오지 못했었습니다!
SOTA로 진행하려면 코드를 수정해야 하나요?? 보내주신 페이지를 그대로 따라 쓰게되면 훈련이 되는 걸까요??

**Comment by Ahmad-noborders** [comment]
@KangSH9776 
please have a look [https://github.com/apache/incubator-mxnet/issues/4431](url)
it solved my problem
